plugins: inline duplicates
directory: /media/music
import:
    write: yes
    move: yes
paths: 
    default: %if{$albumartist,$albumartist,$artist}/%if{$year,$year }${album}/%if{$multidisc,%if{$disctitle,$disctitle,Disc $disc}/}$track $title
    comp: compilations/%if{$year,$year }${album}/%if{$multidisc,%if{$disctitle,$disctitle,Disc $disc}/}$track $title
    singleton: non-album/$artist/$title

item_fields:
    multidisc: 1 if disctotal > 1 else 0
